"""cambio

Revision ID: 2788fb4a6f23
Revises: ef4e11c0aacf
Create Date: 2024-11-21 11:32:49.616152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2788fb4a6f23'
down_revision = 'ef4e11c0aacf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('telefono')
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
